<a href="https://colab.research.google.com/github/heitorabqg/datascientist/blob/master/statisticsHAUniformDist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Statistics
# Heitor Albuquerque

import numpy as np
import matplotlib.pyplot as plt


# Uniform Distribution

# PMF : probability mass function
# f_k [k] = 1/(n-m+1) , if m <= k <= n; 0 , otherwise

# lets say m = 3 and n = 10
m = 3
n = 10
c = 1/(n - m + 1)

f_ku = np.ones(n-m+1)*c
f_ku = f_ku.reshape(1,-1)
print("The values of f_k are \n",f_k)

# plot from 0 to L
L = 20

x = np.arange(0,L+1)
x = x.reshape(1,-1)

print("The values of x are\n", x)

f_kz = np.zeros(m)
f_kz = f_kz.reshape(1,-1)
print("The values of f_z are \n",f_kz)



The values of f_k are 
 [[0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]]
The values of x are
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The values of f_z are 
 [[0. 0. 0.]]
